//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Gramatica/Language.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Analizador {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LanguageParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.declaraciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaraciones([NotNull] LanguageParser.DeclaracionesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionExplicita</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionExplicita([NotNull] LanguageParser.DeclaracionExplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionPorDefecto</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionPorDefecto([NotNull] LanguageParser.DeclaracionPorDefectoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionImplicita</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionImplicita([NotNull] LanguageParser.DeclaracionImplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionArregloExplicita</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_arreglo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionArregloExplicita([NotNull] LanguageParser.DeclaracionArregloExplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionArregloPorDefecto</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_arreglo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionArregloPorDefecto([NotNull] LanguageParser.DeclaracionArregloPorDefectoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionMatrizExplicita</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_matriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionMatrizExplicita([NotNull] LanguageParser.DeclaracionMatrizExplicitaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.dimensiones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimensiones([NotNull] LanguageParser.DimensionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.contenido_matriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContenido_matriz([NotNull] LanguageParser.Contenido_matrizContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.elementos_matriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementos_matriz([NotNull] LanguageParser.Elementos_matrizContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.elemento_matriz"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElemento_matriz([NotNull] LanguageParser.Elemento_matrizContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.lista_valores"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_valores([NotNull] LanguageParser.Lista_valoresContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionFuncion</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_funciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionFuncion([NotNull] LanguageParser.DeclaracionFuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametros([NotNull] LanguageParser.ParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.tipo_funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo_funcion([NotNull] LanguageParser.Tipo_funcionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DeclaracionStruct</c>
	/// labeled alternative in <see cref="LanguageParser.declaracion_struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaracionStruct([NotNull] LanguageParser.DeclaracionStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.atributos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtributos([NotNull] LanguageParser.AtributosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.tipo_struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo_struct([NotNull] LanguageParser.Tipo_structContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpresionSentencia</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpresionSentencia([NotNull] LanguageParser.ExpresionSentenciaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaPrintln</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaPrintln([NotNull] LanguageParser.FuncionEmbebidaPrintlnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Bloque</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloque([NotNull] LanguageParser.BloqueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaIf</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaIf([NotNull] LanguageParser.SentenciaIfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaSwitch</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaSwitch([NotNull] LanguageParser.SentenciaSwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaForSimple</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaForSimple([NotNull] LanguageParser.SentenciaForSimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaForCompuesta</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaForCompuesta([NotNull] LanguageParser.SentenciaForCompuestaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaForRange</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaForRange([NotNull] LanguageParser.SentenciaForRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaBreak</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaBreak([NotNull] LanguageParser.SentenciaBreakContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaContinue</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaContinue([NotNull] LanguageParser.SentenciaContinueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SentenciaReturn</c>
	/// labeled alternative in <see cref="LanguageParser.sentencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciaReturn([NotNull] LanguageParser.SentenciaReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.casos_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCasos_switch([NotNull] LanguageParser.Casos_switchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.default_switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_switch([NotNull] LanguageParser.Default_switchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.for_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_init([NotNull] LanguageParser.For_initContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionVariable</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionVariable([NotNull] LanguageParser.AsignacionVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoMatriz</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoMatriz([NotNull] LanguageParser.AccesoMatrizContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionInstancia</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionInstancia([NotNull] LanguageParser.AsignacionInstanciaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionMatriz</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionMatriz([NotNull] LanguageParser.AsignacionMatrizContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Booleano</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleano([NotNull] LanguageParser.BooleanoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaSlicesIndex</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaSlicesIndex([NotNull] LanguageParser.FuncionEmbebidaSlicesIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegacionUnaria</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegacionUnaria([NotNull] LanguageParser.NegacionUnariaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionArreglo</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionArreglo([NotNull] LanguageParser.AsignacionArregloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SumaResta</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumaResta([NotNull] LanguageParser.SumaRestaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicoAnd</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicoAnd([NotNull] LanguageParser.LogicoAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionVariableSuma</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionVariableSuma([NotNull] LanguageParser.AsignacionVariableSumaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoArreglo</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoArreglo([NotNull] LanguageParser.AccesoArregloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaStringsJoin</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaStringsJoin([NotNull] LanguageParser.FuncionEmbebidaStringsJoinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoStruct</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoStruct([NotNull] LanguageParser.AccesoStructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicoOr</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicoOr([NotNull] LanguageParser.LogicoOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal([NotNull] LanguageParser.DecimalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Relacional</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelacional([NotNull] LanguageParser.RelacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CreacionArreglo</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreacionArreglo([NotNull] LanguageParser.CreacionArregloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LlamadaFuncion</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaFuncion([NotNull] LanguageParser.LlamadaFuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionAtributoInstancia</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionAtributoInstancia([NotNull] LanguageParser.AsignacionAtributoInstanciaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaAtoi</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaAtoi([NotNull] LanguageParser.FuncionEmbebidaAtoiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiplicacionDivisionModulo</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicacionDivisionModulo([NotNull] LanguageParser.MultiplicacionDivisionModuloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IgualdadDesigualdad</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIgualdadDesigualdad([NotNull] LanguageParser.IgualdadDesigualdadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignacionVariableResta</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignacionVariableResta([NotNull] LanguageParser.AsignacionVariableRestaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parentesis</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesis([NotNull] LanguageParser.ParentesisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Cadena</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCadena([NotNull] LanguageParser.CadenaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NegacionLogica</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegacionLogica([NotNull] LanguageParser.NegacionLogicaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Caracter</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaracter([NotNull] LanguageParser.CaracterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaReflectTypeOf</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaReflectTypeOf([NotNull] LanguageParser.FuncionEmbebidaReflectTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Entero</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntero([NotNull] LanguageParser.EnteroContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaParseFloat</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaParseFloat([NotNull] LanguageParser.FuncionEmbebidaParseFloatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaLen</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaLen([NotNull] LanguageParser.FuncionEmbebidaLenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionEmbebidaAppend</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionEmbebidaAppend([NotNull] LanguageParser.FuncionEmbebidaAppendContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Decremento</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecremento([NotNull] LanguageParser.DecrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Incremento</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncremento([NotNull] LanguageParser.IncrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identificador</c>
	/// labeled alternative in <see cref="LanguageParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentificador([NotNull] LanguageParser.IdentificadorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.acceso_len"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceso_len([NotNull] LanguageParser.Acceso_lenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.atributos_instancia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtributos_instancia([NotNull] LanguageParser.Atributos_instanciaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.llamada"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamada([NotNull] LanguageParser.LlamadaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LanguageParser.argumento"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumento([NotNull] LanguageParser.ArgumentoContext context);
}
} // namespace Analizador
